name: LockDemo API (Windows App Service)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
          include-prerelease: true

      - name: Restore
        run: dotnet restore .\LockDemo.ApiService\LockDemo.ApiService.csproj

      - name: Build
        run: dotnet build .\LockDemo.ApiService\LockDemo.ApiService.csproj --configuration Release --no-restore

      - name: Publish self-contained (win-x64)
        run: >
          dotnet publish .\LockDemo.ApiService\LockDemo.ApiService.csproj
          -c Release
          -o "${{ github.workspace }}\publish"
          -r win-x64
          --self-contained true
          /p:PublishSingleFile=true
          /p:PublishTrimmed=false
          /p:EnableCompressionInSingleFile=true
          /p:InvariantGlobalization=false

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-publish
          path: ${{ github.workspace }}\publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-publish
          path: .\publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "LockDemo-Portfolio-Mathszoke"
          package: ".\\publish"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_LOCKDEMO }}
