name: LockDemo API

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
          include-prerelease: true

      - name: Restore
        run: dotnet restore ./LockDemo.ApiService/LockDemo.ApiService.csproj

      - name: Build
        run: dotnet build ./LockDemo.ApiService/LockDemo.ApiService.csproj --configuration Release --no-restore

      - name: Publish
        run: >
          dotnet publish ./LockDemo.ApiService/LockDemo.ApiService.csproj
          -c Release
          -o "$GITHUB_WORKSPACE/publish"
          -r linux-x64
          --self-contained true
          /p:PublishSingleFile=true
          /p:PublishTrimmed=false
          /p:InvariantGlobalization=false
          --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-publish
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-publish
          path: ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "LockDemo-Portfolio"
          package: "./publish"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_LOCKDEMO }}